- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: 
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: toadzbot
        spec:
          serviceName: toadzbot
          template:
            metadata:
              labels:
                app: toadzbot
            spec:
              containers:
              - image: "{{ image }}"
                name: toadzbot
                env:
                - name: MYSQL_HOST
                  value: mysql
                - name: MYSQL_PORT
                  value: "3306"
          selector:
            matchLabels:
              app: toadzbot
      validate_certs: no
      namespace: discordbots
